"""SQLAlchemy ORM models.

These mirror ``migrations/0001_initial.sql``; they do not define it. The SQL is
the source of truth — it holds the CHECK constraints and the immutability
trigger that carry two of the four invariants, and none of that can be
expressed faithfully in ORM metadata.

Consequence worth stating: **do not use ``Base.metadata.create_all()``.** It
would produce a schema without the constraints or the trigger, which is exactly
the schema in which invariants #1 and #4 are unenforced — and it would look
fine. Always apply the migration.
"""

from __future__ import annotations

from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    ARRAY,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    ForeignKeyConstraint,
    Integer,
    LargeBinary,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from app.config import get_settings
from app.domain.enums import (
    ArticleStatus,
    ContactKind,
    ContactStatus,
    RunStatus,
    StudyType,
    Subject,
    UserRole,
    Verdict,
)

#: Read once at import. Must match the applied migration's ``vector(N)``;
#: ``Settings.validate_embedding_dim`` checks it against the live provider at
#: startup.
EMBEDDING_DIM = get_settings().embedding_dim

#: Primary keys are generated by Postgres, not by the ORM.
#:
#: Without ``server_default`` SQLAlchemy sends an explicit NULL for any column
#: it has no Python-side value for, so the database's own DEFAULT never gets a
#: chance to fire and the insert fails on the NOT NULL constraint. That applies
#: to every column the migration defaults: ids, timestamps, and the boolean and
#: counter defaults below.
UUID_PK = UUID(as_uuid=False)
GEN_UUID = text("gen_random_uuid()")

#: Every nullable JSONB column. **Use this, not bare ``JSONB``.**
#:
#: SQLAlchemy's JSON types default to ``none_as_null=False``, which persists a
#: Python ``None`` as the JSON literal ``null`` rather than as SQL ``NULL``.
#: The two are not interchangeable: ``COALESCE(edited_content, original_content)``
#: returns JSON ``null`` for a row that has never been edited, and ``WHERE error
#: IS NULL`` matches no succeeded stage. Both read as "a value is present".
#:
#: Python-side readers hide this — ``json.loads('null')`` is ``None``, so
#: ``edited_content or original_content`` behaves correctly and every current
#: caller happens to take that path. The bug only appears when someone writes
#: the SQL that ``migrations/0001_initial.sql`` and ``services/card.py`` both
#: document as the mechanism, which is exactly when it is least expected.
NullableJSONB = JSONB(none_as_null=True)


def pg_enum(enum_class: type, name: str) -> Enum:
    """Bind a Python enum to a Postgres enum type by **value**, not name.

    SQLAlchemy defaults to persisting the enum's *member name*
    (``VALIDATION_FAILED``), but the migration declares the type with lowercase
    *values* (``validation_failed``). Without ``values_callable`` every read of
    a status column raises ``KeyError``, and every write stores a label the
    Postgres type rejects.

    ``create_type=False`` because the migration owns the type; letting the ORM
    try to create it would conflict on a second run.
    """
    return Enum(
        enum_class,
        name=name,
        values_callable=lambda enum: [member.value for member in enum],
        create_type=False,
    )


class Base(DeclarativeBase):
    """Declarative base. See module docstring — never ``create_all()``."""


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[UserRole] = mapped_column(pg_enum(UserRole, "user_role"), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Source(Base):
    """A cached paper. Also a row in the vector store."""

    __tablename__ = "sources"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    pmid: Mapped[str | None] = mapped_column(Text)
    doi: Mapped[str | None] = mapped_column(Text)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    abstract: Mapped[str] = mapped_column(Text, nullable=False)
    journal: Mapped[str | None] = mapped_column(Text)
    year: Mapped[int | None] = mapped_column(Integer)
    study_type: Mapped[StudyType] = mapped_column(pg_enum(StudyType, "study_type"))
    raw_study_type: Mapped[str | None] = mapped_column(Text)
    citation_count: Mapped[int | None] = mapped_column(Integer)
    url: Mapped[str | None] = mapped_column(Text)
    source_api: Mapped[str] = mapped_column(Text, nullable=False)
    #: Null until the abstract has been embedded, or after a provider change
    #: invalidates the old vector. Deliberately **not** indexed: the only
    #: vector query re-ranks one run's candidates by id and sorts exactly, so
    #: an ANN index cannot be chosen. The measurements are in
    #: ``migrations/0001_initial.sql``, beside the index it declines to create.
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    embedding_model: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    #: Detection time, not the journal's retraction date — neither PubMed nor
    #: Crossref reliably exposes the latter. Set by scripts/check_retractions.py.
    retracted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    #: An expression of concern: under investigation, not withdrawn. Recorded
    #: rather than refused, because the paper may yet be exonerated.
    concern_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    #: NULL means nobody has *successfully* asked — which is not "asked and it
    #: is fine". Written only when a provider actually answered, so a sweep
    #: that reached nothing cannot be mistaken for one that verified everything.
    #: See retrieval/retractions.py.
    retraction_checked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    retraction_note: Mapped[str | None] = mapped_column(Text)

    @property
    def resolved_url(self) -> str:
        """A link that always works.

        Prefers the provider's own URL, then DOI, then PubMed. A source row
        cannot exist without a PMID or DOI (there is a CHECK constraint), so
        this can never return empty.
        """
        if self.url:
            return self.url
        if self.doi:
            return f"https://doi.org/{self.doi}"
        return f"https://pubmed.ncbi.nlm.nih.gov/{self.pmid}/"


class Article(Base):
    __tablename__ = "articles"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    slug: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ArticleStatus] = mapped_column(pg_enum(ArticleStatus, "article_status"))

    topic: Mapped[str] = mapped_column(Text, nullable=False)
    source_blurb: Mapped[str | None] = mapped_column(Text)
    product: Mapped[str] = mapped_column(Text, nullable=False)
    target_claims: Mapped[list[str]] = mapped_column(ARRAY(Text))
    ingredients: Mapped[list[str]] = mapped_column(ARRAY(Text))

    headline: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    verdict: Mapped[Verdict] = mapped_column(pg_enum(Verdict, "verdict"))
    verdict_qualifier: Mapped[str | None] = mapped_column(Text)

    #: Immutable. A DB trigger rejects any UPDATE that changes it — do not
    #: attempt to write it after PersistStage.
    original_content: Mapped[dict] = mapped_column(JSONB, nullable=False)
    edited_content: Mapped[dict | None] = mapped_column(NullableJSONB)

    card_headline: Mapped[str | None] = mapped_column(Text)
    card_excerpt: Mapped[str | None] = mapped_column(Text)
    card_verdict: Mapped[Verdict | None] = mapped_column(pg_enum(Verdict, "verdict"))
    #: The first image in the approved body, materialised at publish time by
    #: the same rule as the other card columns: derived, never a separate
    #: upload. NULL is the normal case — the feed draws a typographic tile.
    card_image: Mapped[str | None] = mapped_column(Text)
    card_image_alt: Mapped[str | None] = mapped_column(Text)

    #: Both frames of the pipeline's generated illustration, plus the prompt,
    #: model and seed that produced them — see ``domain/contracts.Illustration``.
    #: NULL is normal: every article written before this existed, every run with
    #: no image key, and every run whose generation failed.
    #:
    #: ``lead`` is *also* in ``original_content`` as an ordinary image node, so
    #: it is edited and checked like any other picture. ``cover`` is not in the
    #: document at all — it is the portrait framing for the feed tile, and this
    #: column is the only record of it. ``services/card.py`` will only use it
    #: while ``lead.src`` is still the document's first image; that pairing is
    #: what keeps the tile a reframing of the article's own picture rather than
    #: an independent one.
    #:
    #: ``NullableJSONB``, not bare ``JSONB``. It matters here specifically:
    #: ``derive_card`` tests this value for truthiness, and the JSON literal
    #: ``null`` a bare column would store is a dict-shaped truthy value in SQL.
    generated_imagery: Mapped[dict | None] = mapped_column(NullableJSONB)

    #: Set by a reviewer, not by the pipeline. See ``Subject``.
    subject: Mapped[Subject | None] = mapped_column(pg_enum(Subject, "subject"))

    evidence_grade: Mapped[StudyType] = mapped_column(pg_enum(StudyType, "study_type"))
    validation_report: Mapped[dict | None] = mapped_column(NullableJSONB)

    reviewed_by: Mapped[str | None] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id"))
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    rejection_reason: Mapped[str | None] = mapped_column(Text)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    #: A cited source has been retracted. The article stays `published` — this
    #: raises a banner and puts the row in front of a reviewer, who decides.
    #: Automatic withdrawal would be the machine deciding what the public sees,
    #: which is the thing invariant #1 exists to prevent, pointed the other way.
    retraction_flagged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    #: Which handles and sources triggered the flag, so the console can point
    #: at the paragraph rather than at the article.
    retraction_detail: Mapped[dict | None] = mapped_column(NullableJSONB)

    pipeline_run_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    sources: Mapped[list[ArticleSource]] = relationship(back_populates="article")

    @property
    def display_content(self) -> dict:
        """What the reader sees: the human-approved version when one exists."""
        return self.edited_content or self.original_content


class ArticleSource(Base):
    """Provenance: which paper backed which claim, under which handle."""

    __tablename__ = "article_sources"

    article_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("articles.id"), primary_key=True
    )
    source_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("sources.id"), primary_key=True
    )
    claim: Mapped[str] = mapped_column(Text, primary_key=True)
    citation_handle: Mapped[str] = mapped_column(String(8), nullable=False)
    was_cited: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    relevance_score: Mapped[float | None] = mapped_column(Float)

    article: Mapped[Article] = relationship(back_populates="sources")
    source: Mapped[Source] = relationship()


class PipelineRun(Base):
    __tablename__ = "pipeline_runs"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    topic: Mapped[str] = mapped_column(Text, nullable=False)
    source_blurb: Mapped[str | None] = mapped_column(Text)
    status: Mapped[RunStatus] = mapped_column(pg_enum(RunStatus, "run_status"))
    article_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    error: Mapped[dict | None] = mapped_column(NullableJSONB)
    #: Rollup of the per-stage ledger below, so "what did this run consume" is
    #: one row read. Cannot be priced on its own: the stages may have run on
    #: different models. See PipelineStageRun and app/llm/pricing.py.
    input_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    output_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cache_read_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cache_write_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    requested_by: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    #: Attempts started, incremented when a worker claims the run.
    attempts: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    #: Earliest time this run may be claimed; NULL means now. Set when a
    #: retryable failure requeues the run — see orchestrator._requeue_run.
    next_attempt_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    #: Last sign of life from the worker holding this run, pinged on a timer
    #: for as long as it is `running`. A frozen heartbeat is how a killed
    #: worker is told apart from a slow one — see runner._recover_stale_runs.
    heartbeat_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class PipelineStageRun(Base):
    __tablename__ = "pipeline_stage_runs"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("pipeline_runs.id"))
    stage: Mapped[str] = mapped_column(Text, nullable=False)
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    #: Which attempt of the run this row belongs to. Rows are kept per attempt
    #: rather than overwritten — diagnosing a run that succeeded on its third
    #: try means seeing what the first two did.
    attempt: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    status: Mapped[RunStatus] = mapped_column(pg_enum(RunStatus, "run_status"))
    error: Mapped[dict | None] = mapped_column(NullableJSONB)
    metrics: Mapped[dict | None] = mapped_column(NullableJSONB)
    #: Provider-namespaced id of the model this stage called, e.g.
    #: `anthropic/claude-sonnet-5`. NULL for the four stages that call no model.
    #: The join key into app/llm/pricing.py — a bare name would not distinguish
    #: a local model (free) from a hosted one nobody has priced yet.
    model: Mapped[str | None] = mapped_column(Text)
    #: What that call consumed. Kept as four columns rather than one total
    #: because they are priced at four different rates, an order of magnitude
    #: apart in both directions: a cache read is a tenth of a fresh input token,
    #: a cache write a quarter more than one. Written even when the stage
    #: failed — a truncated response burns the whole output budget and produces
    #: nothing, which is the most expensive way a run can end.
    input_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    output_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cache_read_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    cache_write_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Reader(Base):
    """A public reader's account.

    Separate from :class:`User` on purpose — see the note in
    ``migrations/0002_readers_and_subjects.sql``. ``users`` is the reviewer
    roster and ``articles.reviewed_by`` is a foreign key into it, so a row
    there is a claim about who is answerable for a published article. Readers
    sign themselves up; a reader id can never satisfy ``require_reviewer``
    because it is not in ``users`` at all.
    """

    __tablename__ = "readers"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    #: Which subjects to lift to the top of this reader's feed. Ordering, not
    #: filtering: everything else still appears below.
    interests: Mapped[list[Subject]] = mapped_column(
        ARRAY(pg_enum(Subject, "subject")), server_default=text("'{}'")
    )
    newsletter: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class ReaderFolder(Base):
    """A named shelf. Every reader gets one called "Saved" at signup."""

    __tablename__ = "reader_folders"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    reader_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("readers.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class ReaderSave(Base):
    """One article on one reader's shelf.

    ``(reader_id, article_id)`` is the primary key, so moving an article
    between folders is an update of ``folder_id`` rather than a second row —
    the same article cannot accumulate a copy per folder. The composite foreign
    key on ``(folder_id, reader_id)`` is what makes "you can only save into
    your own folder" a database fact rather than a check every handler has to
    remember.
    """

    __tablename__ = "reader_saves"

    reader_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("readers.id", ondelete="CASCADE"),
        primary_key=True,
    )
    article_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("articles.id", ondelete="CASCADE"),
        primary_key=True,
    )
    folder_id: Mapped[str] = mapped_column(UUID(as_uuid=False), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    __table_args__ = (
        ForeignKeyConstraint(
            ["folder_id", "reader_id"],
            ["reader_folders.id", "reader_folders.reader_id"],
            ondelete="CASCADE",
        ),
    )


class ContactRequest(Base):
    """A "Let us know" submission: a claim to check, or a topic to cover.

    Written unauthenticated from the public site, read only in the console.
    No foreign key to ``readers`` — a request is worth having from someone who
    never signs up, and the email on the row is how we reply either way.
    """

    __tablename__ = "contact_requests"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    kind: Mapped[ContactKind] = mapped_column(pg_enum(ContactKind, "contact_kind"))
    name: Mapped[str | None] = mapped_column(Text)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    link: Mapped[str | None] = mapped_column(Text)
    note: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ContactStatus] = mapped_column(pg_enum(ContactStatus, "contact_status"))
    handled_by: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("users.id")
    )
    handled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class MediaObject(Base):
    """Image bytes, keyed by their own SHA-256.

    The store behind ``services/media.py``. Deliberately unrelated to
    ``articles``: an image is referenced by URL from inside a document, and the
    same bytes may be embedded by several drafts or by none. See
    ``migrations/0004_media_objects.sql`` for why a column on ``articles``
    cannot work — the short version is that ILLUSTRATE stores pictures two
    stages before the article row exists.

    ``digest`` is the primary key rather than a surrogate, which is what makes
    storing the same image twice a no-op rather than a duplicate.
    """

    __tablename__ = "media_objects"

    digest: Mapped[str] = mapped_column(Text, primary_key=True)
    #: One of png/jpg/gif/webp, decided by sniffing ``data``'s leading bytes.
    #: The content type served is derived from this via ``media.CONTENT_TYPES``
    #: rather than stored, so there is one definition of that mapping.
    extension: Mapped[str] = mapped_column(Text, nullable=False)
    data: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
