"""SQLAlchemy ORM models.

These mirror ``migrations/0001_initial.sql``; they do not define it. The SQL is
the source of truth — it holds the CHECK constraints and the immutability
trigger that carry two of the four invariants, and none of that can be
expressed faithfully in ORM metadata.

Consequence worth stating: **do not use ``Base.metadata.create_all()``.** It
would produce a schema without the constraints or the trigger, which is exactly
the schema in which invariants #1 and #4 are unenforced — and it would look
fine. Always apply the migration.
"""

from __future__ import annotations

from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    ARRAY,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from app.config import get_settings
from app.domain.enums import ArticleStatus, RunStatus, StudyType, UserRole, Verdict

#: Read once at import. Must match the applied migration's ``vector(N)``;
#: ``Settings.validate_embedding_dim`` checks it against the live provider at
#: startup.
EMBEDDING_DIM = get_settings().embedding_dim

#: Primary keys are generated by Postgres, not by the ORM.
#:
#: Without ``server_default`` SQLAlchemy sends an explicit NULL for any column
#: it has no Python-side value for, so the database's own DEFAULT never gets a
#: chance to fire and the insert fails on the NOT NULL constraint. That applies
#: to every column the migration defaults: ids, timestamps, and the boolean and
#: counter defaults below.
UUID_PK = UUID(as_uuid=False)
GEN_UUID = text("gen_random_uuid()")


def pg_enum(enum_class: type, name: str) -> Enum:
    """Bind a Python enum to a Postgres enum type by **value**, not name.

    SQLAlchemy defaults to persisting the enum's *member name*
    (``VALIDATION_FAILED``), but the migration declares the type with lowercase
    *values* (``validation_failed``). Without ``values_callable`` every read of
    a status column raises ``KeyError``, and every write stores a label the
    Postgres type rejects.

    ``create_type=False`` because the migration owns the type; letting the ORM
    try to create it would conflict on a second run.
    """
    return Enum(
        enum_class,
        name=name,
        values_callable=lambda enum: [member.value for member in enum],
        create_type=False,
    )


class Base(DeclarativeBase):
    """Declarative base. See module docstring — never ``create_all()``."""


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    email: Mapped[str] = mapped_column(Text, nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[UserRole] = mapped_column(pg_enum(UserRole, "user_role"), nullable=False)
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Source(Base):
    """A cached paper. Also a row in the vector store."""

    __tablename__ = "sources"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    pmid: Mapped[str | None] = mapped_column(Text)
    doi: Mapped[str | None] = mapped_column(Text)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    abstract: Mapped[str] = mapped_column(Text, nullable=False)
    journal: Mapped[str | None] = mapped_column(Text)
    year: Mapped[int | None] = mapped_column(Integer)
    study_type: Mapped[StudyType] = mapped_column(pg_enum(StudyType, "study_type"))
    raw_study_type: Mapped[str | None] = mapped_column(Text)
    citation_count: Mapped[int | None] = mapped_column(Integer)
    url: Mapped[str | None] = mapped_column(Text)
    source_api: Mapped[str] = mapped_column(Text, nullable=False)
    #: Cosine-indexed by sources_embedding_hnsw. Null until the abstract has
    #: been embedded, or after a provider change invalidates the old vector.
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    embedding_model: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    @property
    def resolved_url(self) -> str:
        """A link that always works.

        Prefers the provider's own URL, then DOI, then PubMed. A source row
        cannot exist without a PMID or DOI (there is a CHECK constraint), so
        this can never return empty.
        """
        if self.url:
            return self.url
        if self.doi:
            return f"https://doi.org/{self.doi}"
        return f"https://pubmed.ncbi.nlm.nih.gov/{self.pmid}/"


class Article(Base):
    __tablename__ = "articles"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    slug: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[ArticleStatus] = mapped_column(pg_enum(ArticleStatus, "article_status"))

    topic: Mapped[str] = mapped_column(Text, nullable=False)
    source_blurb: Mapped[str | None] = mapped_column(Text)
    product: Mapped[str] = mapped_column(Text, nullable=False)
    target_claims: Mapped[list[str]] = mapped_column(ARRAY(Text))
    ingredients: Mapped[list[str]] = mapped_column(ARRAY(Text))

    headline: Mapped[str] = mapped_column(Text, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    verdict: Mapped[Verdict] = mapped_column(pg_enum(Verdict, "verdict"))
    verdict_qualifier: Mapped[str | None] = mapped_column(Text)

    #: Immutable. A DB trigger rejects any UPDATE that changes it — do not
    #: attempt to write it after PersistStage.
    original_content: Mapped[dict] = mapped_column(JSONB, nullable=False)
    edited_content: Mapped[dict | None] = mapped_column(JSONB)

    card_headline: Mapped[str | None] = mapped_column(Text)
    card_excerpt: Mapped[str | None] = mapped_column(Text)
    card_verdict: Mapped[Verdict | None] = mapped_column(pg_enum(Verdict, "verdict"))

    evidence_grade: Mapped[StudyType] = mapped_column(pg_enum(StudyType, "study_type"))
    validation_report: Mapped[dict | None] = mapped_column(JSONB)

    reviewed_by: Mapped[str | None] = mapped_column(UUID(as_uuid=False), ForeignKey("users.id"))
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    rejection_reason: Mapped[str | None] = mapped_column(Text)
    published_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    pipeline_run_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    sources: Mapped[list[ArticleSource]] = relationship(back_populates="article")

    @property
    def display_content(self) -> dict:
        """What the reader sees: the human-approved version when one exists."""
        return self.edited_content or self.original_content


class ArticleSource(Base):
    """Provenance: which paper backed which claim, under which handle."""

    __tablename__ = "article_sources"

    article_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("articles.id"), primary_key=True
    )
    source_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("sources.id"), primary_key=True
    )
    claim: Mapped[str] = mapped_column(Text, primary_key=True)
    citation_handle: Mapped[str] = mapped_column(String(8), nullable=False)
    was_cited: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    relevance_score: Mapped[float | None] = mapped_column(Float)

    article: Mapped[Article] = relationship(back_populates="sources")
    source: Mapped[Source] = relationship()


class PipelineRun(Base):
    __tablename__ = "pipeline_runs"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    topic: Mapped[str] = mapped_column(Text, nullable=False)
    source_blurb: Mapped[str | None] = mapped_column(Text)
    status: Mapped[RunStatus] = mapped_column(pg_enum(RunStatus, "run_status"))
    article_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    error: Mapped[dict | None] = mapped_column(JSONB)
    input_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    output_tokens: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    requested_by: Mapped[str | None] = mapped_column(UUID(as_uuid=False))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class PipelineStageRun(Base):
    __tablename__ = "pipeline_stage_runs"

    id: Mapped[str] = mapped_column(UUID_PK, primary_key=True, server_default=GEN_UUID)
    run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("pipeline_runs.id"))
    stage: Mapped[str] = mapped_column(Text, nullable=False)
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[RunStatus] = mapped_column(pg_enum(RunStatus, "run_status"))
    error: Mapped[dict | None] = mapped_column(JSONB)
    metrics: Mapped[dict | None] = mapped_column(JSONB)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
